# Generated by Django 5.2 on 2026-04-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64)),
                ('tjm', models.PositiveIntegerField(default=0)),
                ('who', models.CharField(blank=True, max_length=128)),
                ('expertise', models.TextField(blank=True)),
                ('message_genere', models.TextField(blank=True)),
                ('url_source', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('civilities', models.ManyToManyField(to='candidacy.civility')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='candidacy.contract')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='candidacy.position')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='candidacy.status')),
                ('technologies', models.ManyToManyField(to='candidacy.technology')),
            ],
        ),
    ]
